---
- name: Install EXE package on Windows
  hosts: all
  remote_user: ansible
  tasks:

    - name: Copy EXE file to Windows host
      win_copy:
        src: ~/tosend/7z2408-x64.exe
        dest: C:\temp\ansible_deploy.exe

    - name: Run exe installer
      win_shell: 'C:\temp\ansible_deploy.exe /S'
      args:
        executable: cmd

    - name: Verify if package installed successfully
      win_shell: |
        Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where-Object { $_.DisplayName -like "*7-Zip*" }
      register: exe_check
      changed_when: false

    - name: Show installation result
      debug:
        var: exe_check